name: i_component_module
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.1
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator:
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/fonts/
    - assets/fonts/Be_Vietnam_Pro/

  fonts:
    - family: Be_Vietnam_Pro
      fonts:
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-Black.ttf
          weight: 900
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraBoldItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-Light.ttf
          weight: 300
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-Thin.ttf
          weight: 100
        - asset: assets/fonts/Be_Vietnam_Pro/BeVietnamPro-ThinItalic.ttf
          style: italic
          weight: 100
